name: publrealty
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.3.1
  connectivity: ^3.0.6
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.5
  flutter_html: ^3.0.0-alpha.5
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  get: ^4.6.6
  google_maps_flutter: ^2.2.5
  image_picker: ^0.8.5+3
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  photo_view: ^0.14.0
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik-light.ttf
          weight: 300
        - asset: assets/fonts/rubik-regular.ttf
          weight: 400
        - asset: assets/fonts/rubik-medium.ttf
          weight: 500
        - asset: assets/fonts/rubik-bold.ttf
          weight: 700
        - asset: assets/fonts/rubik-black.ttf
          weight: 900
    - family: Mada
      fonts:
        - asset: assets/fonts/mada-light.ttf
          weight: 300
        - asset: assets/fonts/mada-regular.ttf
          weight: 400
        - asset: assets/fonts/mada-medium.ttf
          weight: 500
        - asset: assets/fonts/mada-bold.ttf
          weight: 700
        - asset: assets/fonts/mada-black.ttf
          weight: 900
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans_Condensed-Light.ttf
        - asset: assets/fonts/OpenSans_Condensed-Regular.ttf
        - asset: assets/fonts/OpenSans_Condensed-Medium.ttf
        - asset: assets/fonts/OpenSans_Condensed-SemiBold.ttf
        - asset: assets/fonts/OpenSans_Condensed-Bold.ttf
        - asset: assets/fonts/OpenSans_Condensed-ExtraBold.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Light.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Regular.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Medium.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Bold.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBold.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Medium.ttf
        - asset: assets/fonts/OpenSans-SemiBold.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
        - asset: assets/fonts/OpenSans_Condensed-LightItalic.ttf
        - asset: assets/fonts/OpenSans_Condensed-Italic.ttf
        - asset: assets/fonts/OpenSans_Condensed-MediumItalic.ttf
        - asset: assets/fonts/OpenSans_Condensed-SemiBoldItalic.ttf
        - asset: assets/fonts/OpenSans_Condensed-BoldItalic.ttf
        - asset: assets/fonts/OpenSans_Condensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-LightItalic.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-Italic.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-MediumItalic.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-SemiBoldItalic.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-BoldItalic.ttf
        - asset: assets/fonts/OpenSans_SemiCondensed-ExtraBoldItalic.ttf
        - asset: assets/fonts/OpenSans-LightItalic.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
  assets:
    - assets/images/logo.png
